from gym.envs.registration import register

register(
	id='Montage-v1',
	entry_point="gym_workflow.envs.scheme.version_1:Version1",
)
register(
	id='Montage-v2',
	entry_point="gym_workflow.envs.scheme.version_2:Version2",
)
register(
	id='Montage-v3',
	entry_point="gym_workflow.envs.scheme.version_3:Version3",
)
register(
	id='Montage-v4',
	entry_point="gym_workflow.envs.scheme.version_4:Version4",
)
register(
	id='Montage-v5',
	entry_point="gym_workflow.envs.scheme.version_5:Version5",
)
register(
	id='Montage-v6',
	entry_point="gym_workflow.envs.scheme.version_6:Version6",
)
register(
	id='Montage-v7',
	entry_point="gym_workflow.envs.scheme.version_7:Version7",
)
register(
	id='Montage-v8',
	entry_point="gym_workflow.envs.scheme.version_8:Version8",
)
register(
	id='Montage-v9',
	entry_point="gym_workflow.envs.scheme.version_9:Version9",
)
register(
	id='Montage-v10',
	entry_point="gym_workflow.envs.scheme.version_10:Version10",
)
register(
	id='Montage-v11',
	entry_point="gym_workflow.envs.scheme.version_11:Version11",
)
register(
	id='Montage-v12',
	entry_point="gym_workflow.envs.scheme.version_12:Version12",
)
